In [1]:
import numpy as np


In [2]:
# Creating a 1D array
one_d_array = [1, 2, 3, 4, 5]

# Accessing elements
print(one_d_array[0])  # Output: 1
print(one_d_array[2])  # Output: 3

1
3


In [3]:
import numpy as np

# Creating a 1D array
one_d_array = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating a 3D array
three_d_array = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [4]:
# Creating a 2D array
two_d_array = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Accessing elements
print(two_d_array[1][2])  # Output: 6

6


Accessing Elements
In Python, you can access elements in a 2D array using two indices:

The first index refers to the row number.
The second index refers to the column number within that row.

In [ ]:
#  creating array with numpy

In [8]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6,),(4,5,6,7,8,9)])

In [9]:
a.shape

(6,)

In [10]:
b.shape

(2, 6)

In [11]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


(2, 6)

In [ ]:
# initalize arrays


In [13]:
zeros = np.zeros((3,4)) # rows ,columns
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
full = np.full((2,5),5)
print(full)

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [18]:
identity =np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('int64')

In [ ]:
# array attributes
a.shape
len(a) # length  of array

6

In [ ]:
a.ndim # give the dimension of array

1

In [23]:
a.size # give us the number of elements

6

In [26]:
a

array([1, 2, 3, 4, 5, 6])

In [27]:
b


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [25]:
# basic operations 
g = a-b 
g

array([[ 0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3]])

# part 2 numpy basics

In [1]:
import numpy as np

In [5]:
# Create an empty array with 2 elements
empty = np.empty((2,4)) 
print(empty)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.74303020e-321 7.56592337e-307 9.34588060e-307]]


In [6]:
even = np.arange(0,20,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0, 10, num=5 ,dtype=np.int64)

array([ 0,  2,  5,  7, 10])

In [9]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr
np.sort(arr)
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [15]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [18]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 3d array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [6]:
array_example.size

24

In [7]:
array_example.shape

(3, 2, 4)

In [23]:

# reshape the array
array_example = array_example.reshape(3,4,2)
array_example.shape


(3, 4, 2)

In [24]:

 a= array_example
 a

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [26]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

 # Indexing and slicing

In [28]:
a = np.array([1, 2, 3, 4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a[2:4]

array([3, 4])

In [31]:
a [-4 :-2]

array([5, 6])

In [34]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
b[1]

array([5, 6, 7, 8])

In [36]:
print(a[a < 5])

[1 2 3 4]


In [37]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[2 4 6 8]


In [38]:
c = a[(a > 2) & (a < 11)]
print(c)

[3 4 5 6 7 8]


In [39]:
five_up = (a > 5) | (a == 5)
print(five_up)

[False False False False  True  True  True  True]


In [1]:
import numpy as np

In [3]:
# make an array from existing data
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [5]:
arr1 = a[2:4]
arr1

array([3, 4])

In [6]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [7]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Creating matrices

In [11]:
# create matrix 2 by 3
# create matrix 2 by 3
a = np.array([[2, 3, 4], [5, 6, 7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
# create a mtrix big dimension

In [16]:
b = np.arange(0,100,2 )
b = b.reshape(5,10)
b


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [17]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [19]:
data.max()
data.min()
data.sum()

np.int64(21)

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)  # column wise max
data.max(axis=1) # row wise max

array([2, 5, 6])

In [21]:
data.max(axis=0)  # column wise max

array([5, 6])

In [22]:
data.max(axis=1) # row wise max

array([2, 5, 6])

In [8]:
m = np .arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [9]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [15]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [17]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [18]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
